version: "3"

services:
   db:
    image: mysql:5.7
    volumes:
       - ./mysql/data:/var/lib/mysql
       - ./mysql/mysql_init:/docker-entrypoint-initdb.d
    environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: hackernews
       MYSQL_USER: djur
       MYSQL_PASSWORD: admin
    ports:
       - "3306:3306"
   backend:
    image: mikkeldjurhuus/hackernews-backend
    ports:
       - "8081:8081"
    depends_on:
       - db
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "app.py"]
   frontend:
    image: mikkeldjurhuus/hackernews-frontend
    ports:
       - "8080:8080"
    depends_on:
     backend: