version: "3"

services:
   db:
    image: mysql:5.7
    volumes:
       - ./mysql/data:/var/lib/mysql
       - ./mysql/mysql_init:/docker-entrypoint-initdb.d
       - ./mysql/files:/var/lib/mysql-files/
    environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: hackernews
       MYSQL_USER: djur
       MYSQL_PASSWORD: admin
    ports:
       - "3306:3306"
   backend:
    image: mikkeldjurhuus/hackernews-backend
    ports:
       - "8081:8081"
    depends_on:
       - db
   frontend:
    image: mikkeldjurhuus/hackernews-frontend
    ports:
       - "8080:8080"
    depends_on:
       - backend
   prometheus:
    image: prom/prometheus
    volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
       - "9090:9090"
   grafana:
    image: grafana/grafana:4.5.2
    ports:
       - "3000:3000"