version: "2,1"

services:
   db:
    image: mysql:5.7
    volumes:
       - ./mysql/data:/var/lib/mysql
       - ./mysql/mysql_init:/docker-entrypoint-initdb.d
    environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: hackernews
       MYSQL_USER: djur
       MYSQL_PASSWORD: admin
    ports:
       - "3306:3306"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5
   backend:
    image: mikkeldjurhuus/hackernews-backend
    ports:
       - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
       - db
   frontend:
    image: mikkeldjurhuus/hackernews-frontend
    ports:
       - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
     backend:
      condition: service_healthy